- name: installing nginx on local
  hosts: local
  become: yes   # becomes sudo access to install the nginx
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    