- name: install mysql on localhost
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Run mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
    

        