- name: stop nginx service
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: nginx service to be stopped
    ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: yes